// todo - create a fragment from Video to use with project

const mockSchema = `

type Video {
  id: String
  cover: String
  src: String
  filename: String
  size: String
  resolutions: String
  uploadedAt: String
  tags: [String]
}

type ProjectVideos {
  id: String
  cover: String
  version: String
  uploadedAt: String
}

type Project {
  id: String
  name: String
  videos: [ProjectVideos]
}

type AutogeneratedMainType {
  videos: [Video]
  video(id: String): Video
  projects: [Project]
  project(id: String): Project
}

schema {
  query: AutogeneratedMainType
}

`
module.exports = mockSchema
